server:
  port: 8081
  servlet:
    context-path: /alibaba-ai
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: spring-ai-alibaba
    group: ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3-vl:2b
          temperature: 0.8
