server:
  port: 8080
  servlet:
    context-path: /spring-ai
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3-vl:2b
          temperature: 0.8
      init:
        ## 是否在项目启动的时候拉取模型 never: 从不拉取，when-miss: 没有的时候拉取，always: 总是拉取
        pull-model-strategy: never
      embedding:
        options:
          model: qwen3-embedding:0.6b
    vectorstore:
      pgvector:
        initialize-schema: true
        ## Qwen3-Embedding-0.6B 的维度是 1024
        dimensions: 1024
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.178.42.153:5432/postgres?serverTimezone=Asia/Shanghai
    username: postgres
    password:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 32

  application:
    name: spring-ai
    group: ai